services:
  bugsink:
    image: bugsink/bugsink
    container_name: bugsink
    env_file:
      - .env
    ports:
      - "8100:8000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
