
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped

    # CONFIGURACIONES DE SEGURIDAD BÁSICAS
    security_opt:
      - no-new-privileges:true

    # VARIABLES DE ENTORNO SEGURAS
    environment:
      # === CONFIGURACIÓN BÁSICA ===
      - WEBSOCKET_ENABLED=false
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - INVITATION_ORG_NAME=Family
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - DOMAIN=${VAULTWARDEN_DOMAIN}

      # === CONFIGURACIÓN SMTP ===
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

      # === SEGURIDAD AVANZADA ===
      - IP_HEADER=CF-Connecting-IP
      - ICON_SERVICE=internal
      - DISABLE_2FA_REMEMBER=true
      - REQUIRE_DEVICE_EMAIL=true
      - DISABLE_ICON_DOWNLOAD=true

      # === RATE LIMITING ===
      - LOGIN_RATELIMIT_SECONDS=60
      - LOGIN_RATELIMIT_MAX_BURST=5
      - ADMIN_RATELIMIT_SECONDS=300
      - ADMIN_RATELIMIT_MAX_BURST=3

      # === LOGS Y MONITOREO ===
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=false
      - EMERGENCY_ACCESS_ALLOWED=true
      - ORG_EVENTS_ENABLED=true

      # === CONFIGURACIONES ADICIONALES ===
      - ROCKET_WORKERS=2
      - SHOW_PASSWORD_HINT=false
      - PASSWORD_ITERATIONS=200000

    volumes:
      - ./data:/data

    networks:
      homeserver-network:
        ipv4_address: 172.20.0.20

    ports:
      - "8080:80"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/alive || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
